name: finance_guard
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0

  # ✅ Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

  # ✅ Date and formatting
  flutter_datetime_picker_plus: ^2.0.1
  intl: ^0.19.0

  # ✅ Core utilities
  uuid: ^4.4.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.4
  flutter_spinkit: ^5.1.0
  fl_chart: ^0.65.0
  dio: ^5.7.0
  percent_indicator: ^4.2.3


  # ✅ WebView (обновлённая)
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_launcher_icons:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
